Blogging/Blogging/urls.py
from django.contrib import admin
from django.urls import path
from Blog.views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',FirstPage),
    path('SecondPage/',SecondPage,name = 'second'),
    path('temp/',HtmlPage),
    path('allstudent/',Allstudent,name = "alls"),
    path('singledata/',getdata),
    path("details/<int:sid>/",StudentDetail,name='sdetail'),
    path('addition/<int:num1>/<int:num2>/',Add,name ='Add'),

    path('All_category/',AdminPanel,name = 'allc'),
    path('cat_detail/<int:cid>/', Category_detail, name="cdetail"),
    path('testfile/',test,name = 'test'),
    path('dynamic_fun/<int:num>',test1,name = 'test1'),
    path('add_form/',HtmlForm,name='form'),
    path('add_category/',AddCategory,name ='add_cat'),
    path('add_blog/',AddBlog,name ='add_blog'),
    path('Login/', LoginForm, name='login'),
    path('home/', Home, name='home'),
    path('UserPanel', Userpanel, name='upanel'),
    path('logout/', LogoutUser, name='logout'),
     path('Signup/', Signup, name='signup'),
    path('Edit_blog/<int:bid>/', Edit_blog, name='editb'),
path('delete_blog/<int:bid>/', DeleteData, name='delete_b'),

################# New URLs ######################
path('', NewHome, name='newhome'),
path('about/', AboutUs, name='about'),
path('allblog/', AllBlogs, name='blogs'),
path('contact/', ContactUs, name='contact'),
path('blog_detail/<int:bid>/', Newblogdetail, name="bdetail"),
path('blog_comment/<int:bid>/', AddComment, name="comment"),
path('blog_like/<int:bid>/', LikeTheBlog, name="like"),
path('UserPanel', Userpanel, name='upanel'),

]+static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

Blogging/Blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
class Student(models.Model):
    name = models.CharField(max_length=100,null=True)
    email = models.EmailField(max_length=100,null=True)
    mobile = models.CharField(max_length=13,null=True)
    address = models.TextField(null=True)
    branch = models.CharField(max_length=50,default="CS")
    roll_no = models.CharField(max_length=50,null=True,blank=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name


class BlogModel(models.Model):
    usr = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    cat = models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=100,null=True)
    sdes = models.TextField(null=True)
    long_des = models.TextField(null=True)
    date = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.title + " -- " + self.cat.name

class LikeBlog(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, null=True)




class UserDetail(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=100,null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.usr.first_name

class UserComment(models.Model):
    usr = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    blog = models.ForeignKey(BlogModel,on_delete=models.CASCADE,null=True)
    msg = models.TextField(null=True)
    date = models.DateField(null=True)

    def __str__(self):
        return self.usr.first_name + '--' + self.blog.title

Blogging/Blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from .models import *
# Create your views here.

def FirstPage(request):
    name = "vaishnavi"
    return HttpResponse("<h1>Welcome " + name + "</h1>")


def SecondPage(request):
    return HttpResponse("<h1>Welcome to TechSim+</h1>")

def HtmlPage(request):
    slist = ["swagat","Parth","Pragya","Vaishnavi","Chandan"]
    d = {"sdata":slist}
    return render(request, 'index.html',d)


def Allstudent(request):
    data = Student.objects.all() # list of objects[]
    d = {"studentdata":data}
    return render(request,'students.html',d)

def getdata(request):
    data = Student.objects.get(id=3) # single object

    filterdata = Student.objects.filter(branch = "CS")# [] List of objects
    lastob = Student.objects.filter(branch = "CS").last()
    fristob = Student.objects.filter(branch = "CS").first()
    print("filterdata:.....",filterdata)
    d = {"student":data,"filterdata":filterdata}
    return render(request,'single.html',d)

def Add(request,num1,num2):
    print(num1,num2)
    output = num1 + num2
    return HttpResponse("<h1>Output: "+str(output)+"</h1>")

def StudentDetail(request,sid):
    data = Student.objects.get(id = sid)
    d = {"student":data}
    return render(request,'details.html',d)




def test(request):
    return render(request,'test.html')

def test1(request,num):
    num = num + 10
    d = {"num":num}
    return render(request,'test1.html',d)


def HtmlForm(request):
    output = None
    if request.method == "POST":
        d = request.POST
        print(d['num1'])
        print(d['num2'])
        a = int(d['num1'])
        b = int(d['num2'])
        output = a + b
    dic = {"op":output}

    return render(request,'hform.html',dic)


from datetime import date

from django.contrib.auth import authenticate,login,logout

### Project Structure
def Home(request):
    allcat = Category.objects.all()
    d = {"allcat":allcat}
    return render(request,'home.html',d)


# If SuperUser
def AdminPanel(request):
    allcat = Category.objects.all()
    d = {"allcat":allcat}
    return render(request,'allcat.html',d)


def AddCategory(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if not request.user.is_staff:
        return redirect('login')
    if request.method == "POST":
        dic = request.POST
        c = dic['cname']
        Category.objects.create(name = c)
        return redirect('allc')

    return render(request,'add_cat.html')


def Category_detail(request,cid):
    catdata = Category.objects.get(id = cid)
    blogs = BlogModel.objects.filter(cat = catdata)
    d = {"blogs":blogs}
    return render(request,'cat_details.html',d)

# Normal User



def AddBlog(request):
    if not request.user.is_authenticated:
        return redirect('login')
    allcategory = Category.objects.all()
    d = {"allcategory":allcategory}
    if request.method == "POST":
        dic = request.POST
        catid = dic['cat']
        catdata = Category.objects.get(id = catid)
        bname = dic['bname']
        st = dic['short']
        long = dic['long']
        img = request.FILES['img']
        #img_post = dic['img']
        #print(img,img_post)
        td = date.today()
        userdata = request.user
        BlogModel.objects.create(usr = userdata,
                                 cat = catdata,
                                 title = bname,
                                 sdes = st,
                                 long_des =long,
                                 image = img,
                                 date = td)
        return redirect( 'upanel')


    return render(request,'newtemp/blog_add.html',d)



# Logout

def LogoutUser(request):
    logout(request)
    return redirect('newhome')

# SignUp

def Signup(request):
    error = False
    if request.method == "POST":
        d = request.POST
        full = d['fname'].split()
        first = full[0]
        if full[1]:
            last = full[1]
        else:
            last = ""
        mob = d['mob']
        em = d['email']
        u = d['uname']
        p = d['pwd']
        i = request.FILES['img']
        user = User.objects.filter(username = u)
        if user:
            error = True
        else:
            userdata = User.objects.create_user(username=u,password=p,
                                     email=em,first_name = first,
                                     last_name = last)
            UserDetail.objects.create(usr = userdata,image = i,mobile= mob)
            return redirect('login')


    dic = {"error":error}
    return render(request,'newtemp/sign.html',dic)


def Edit_blog(request,bid):
    blogdata = BlogModel.objects.get(id = bid)
    allcategory = Category.objects.all()
    if request.method == "POST":
        dic = request.POST
        catid = dic['cat']
        t = dic['bname']
        s = dic['short']
        l = dic['long']


        file = request.FILES
        if len(file) != 0:
            i = request.FILES['img']
            blogdata.image = i
            blogdata.save()
        '''try:
            i = request.FILES['img']
            blogdata.image = i
            blogdata.save()
        except:
            pass'''


        catdata = Category.objects.get(id = catid)
        blogdata.title = t
        blogdata.sdes = s
        blogdata.long_des = l

        blogdata.cat = catdata
        blogdata.save()
    d = {"blogdata":blogdata,"allcategory":allcategory}
    return render(request,'newtemp/edit.html',d)


def DeleteData(request,bid):
    blogdata = BlogModel.objects.get(id=bid)
    blogdata.delete()
    return redirect('upanel')





###################### New Front End ########################

def NewHome(request):
    allblog = BlogModel.objects.all()
    bigblog = allblog[len(allblog)-1]
    #allblog = allblog[::-1]
    last_four_blog = allblog[:4]
    d = {"bigblog":bigblog,"last_four_blog":last_four_blog}
    return render(request,'newtemp/index.html',d)


def AboutUs(request):
    return render(request, 'newtemp/about.html')

def AllBlogs(request):
    blogs = BlogModel.objects.all()
    d = {"blogs":blogs}
    return render(request,'newtemp/allblog.html',d)

def ContactUs(request):
    return render(request, 'newtemp/contact.html')


def Newblogdetail(request,bid):
    data = BlogModel.objects.get(id = bid)
    userdata = UserDetail.objects.filter(usr = data.usr).first()
    comments = UserComment.objects.filter(blog = data)
    n = comments.count()
    d = {"detail":data,"userdata":userdata,"count":n}
    print(d["userdata"])
    return render(request,'newtemp/single.html',d)


def AddComment(request,bid):
    if not request.user.is_authenticated:
        return redirect('login')
    blogdata = BlogModel.objects.get(id = bid)
    usr = request.user
    td = date.today()
    msg = request.POST['msg']
    UserComment.objects.create(usr = usr,blog = blogdata,date = td,msg = msg)
    return redirect('bdetail',bid)


def LikeTheBlog(request,bid):
    blogdata = BlogModel.objects.get(id=bid)
    user = request.user
    data = LikeBlog.objects.filter(blog = blogdata,usr = user)
    if not data:
        LikeBlog.objects.create(blog = blogdata,usr = request.user)
    else:
        data.delete()

    return redirect('bdetail',bid)


def Userpanel(request):
    if not request.user.is_authenticated:
        return redirect('login')
    userblogs = BlogModel.objects.filter(usr = request.user)
    userdata = UserDetail.objects.get(usr = request.user)
    d = {"blogs":userblogs,"userdata":userdata}

    return render(request, 'newtemp/userpanel.html',d)

def LoginForm(request):
    d = { "wro": "hello"}
    if request.method == "POST":
        dic = request.POST
        u = dic['user']
        p = dic['pwd']
        user = authenticate(username = u,password = p)
        if user:
            login(request,user)
            if request.user.is_staff:
                 return redirect('allc')
            return redirect('newhome')
        else:
            d = {"wrong": "hello"}
            # return HttpResponse("User Not Found or Incorrect Password")


    return render(request,'newtemp/login.html',d)

Blogging/Blog/templates/newtemp/about.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">About Us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About us<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    	<div class="container">
    		<div class="row d-flex">
    			<div class="col-md-6 d-flex">
    				<div class="img d-flex align-self-stretch" style="background-image:url({% static 'images/about.jpg' %});"></div>
    			</div>
    			<div class="col-md-6 pl-md-5 py-5">
    				<div class="row justify-content-start pb-3">
		          <div class="col-md-12 heading-section ftco-animate">
		            <h2 class="mb-4"><span>About Stories</span></h2>
		            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
		          </div>
		        </div>
		    		<div class="row">
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="10">0</strong>
		                <span>Years of Experienced</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="200">0</strong>
		                <span>Foods</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="300">0</strong>
		                <span>Lifestyle</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center py-5 bg-light mb-4">
		              <div class="text">
		                <strong class="number" data-number="40">0</strong>
		                <span>Happy Customers</span>
		              </div>
		            </div>
		          </div>
		        </div>
	        </div>
        </div>
    	</div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-section-about ftco-no-pb bg-darken">
    	<div class="container-fluid">
    		<div class="row">
					<div class="col-sm-6 col-md-6 col-lg-9 order-md-last img py-5" style="background-image: url({% static 'images/bg_3.jpg' %});"></div>

	        <div class="col-sm-6 col-md-6 col-lg-3 py-4 text d-flex align-items-center ftco-animate">
	        	<div class="text-2 py-5 px-4">
	          	<p class="mb-5"><a href="https://vimeo.com/45830194" class="btn-custom popup-vimeo">Watch Video <span class="ion-ios-play ml-4"></span></a></p>
	            <h1 class="mb-5">Roger <br> Bosch</h1>
	            <p class="mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
	            <span class="signature">Roger.Bosch</span>
	          </div>
	        </div>
    		</div>
    	</div>
    </section>

{% endblock %}

Blogging/Blog/templates/newtemp/allblog.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Foods</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Foods <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>


    <section class="ftco-section">
    	<div class="container">
        <div class="row">
        	<div class="col-lg-9">
        		<div class="row">
					{% for i in blogs %}
        			<div class="col-md-4 ftco-animate">
    						<div class="blog-entry">
		    					<a href="{% url 'bdetail' i.id %}" class="img-2"><img src="{{ i.image.url }}" class="img-fluid" alt="Colorlib Template"></a>
			    				<div class="text pt-3">
	    							<p class="meta d-flex"><span class="pr-3">{{ i.usr.first_name }}</span><span class="ml-auto pl-3">March 01, 2018</span></p>
	    							<h3><a href="{% url 'bdetail' i.id %}">{{ i.title }}</a></h3>
	    							<p class="mb-0"><a href="{% url 'bdetail' i.id %}" class="btn btn-black py-2">Read More <span class="icon-arrow_forward ml-4"></span></a></p>
	    						</div>
		    				</div>
    					</div>
					{% endfor %}




        		</div>
        		<div class="row mt-5">
		          <div class="col text-center">
		            <div class="block-27">
		              <ul>
		                <li><a href="#">&lt;</a></li>
		                <li class="active"><span>1</span></li>
		                <li><a href="#">2</a></li>
		                <li><a href="#">3</a></li>
		                <li><a href="#">4</a></li>
		                <li><a href="#">5</a></li>
		                <li><a href="#">&gt;</a></li>
		              </ul>
		            </div>
		          </div>
		        </div>
        	</div>

        	<div class="col-lg-3">
        		<div class="sidebar-wrap">
	        		<div class="sidebar-box p-4 about text-center ftco-animate">
			          <h2 class="heading mb-4">About Me</h2>
			          <img src="{% static 'images/author.jpg' %}" class="img-fluid" alt="Colorlib Template">
			          <div class="text pt-4">
			          	<p>Hi! My name is <strong>Cathy Deon</strong>, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
			          </div>
	        		</div>
	        		<div class="sidebar-box p-4 ftco-animate">
	              <form action="#" class="search-form">
	                <div class="form-group">
	                  <span class="icon icon-search"></span>
	                  <input type="text" class="form-control" placeholder="Search">
	                </div>
	              </form>
	            </div>
	            <div class="sidebar-box categories text-center ftco-animate">
			          <h2 class="heading mb-4">Categories</h2>
			          <ul class="category-image">
			          	<li>
			          		<a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url({% static 'images/category-1.jpg' %});">
			          			<div class="text">
			          				<h3>Foods</h3>
			          			</div>
			          		</a>
			          	</li>
			          	<li>
			          		<a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url({% static 'images/category-2.jpg' %});">
			          			<div class="text">
			          				<h3>Lifestyle</h3>
			          			</div>
			          		</a>
			          	</li>
			          	<li>
			          		<a href="#" class="img d-flex align-items-center justify-content-center text-center" style="background-image: url({% static 'images/category-2.jpg' %});">
			          			<div class="text">
			          				<h3>Others</h3>
			          			</div>
			          		</a>
			          	</li>
			          </ul>
	        		</div>
            </div>
        	</div>
        </div>
    	</div>
    </section>

		
{% endblock %}

Blogging/Blog/templates/newtemp/single.html
{% extends 'newtemp/base.html' %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">{{ detail.title }}</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'newhome' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>{{ detail.title }}<i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 order-lg-last ftco-animate">
            <h2 class="mb-3">{{ detail.title }}

            </h2>
          {% if request.user.first_name %}
            <p><b>{{ detail.likeblog_set.count }} <a href="{% url 'like' detail.id %}"> <i class="fa fa-thumbs-up" style="font-size:25px;"></i></a></b>


            </p>
          {% endif %}

            <p>{{ detail.sdes }}</p>
            <p>
              <img src="{{ detail.image.url }}" alt="" class="img-fluid">
            </p>
            <p>{{ detail.long_des }}</p>



            
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="{{ userdata.image.url }}" alt="{{ detail.usr.first_name }}" width="200px;" height="200px;" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3>{{ detail.usr.first_name }}</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
              </div>
            </div>
    {% if request.user.first_name == detail.usr.first_name %}
            <div>
                 <a href="{% url 'editb' detail.id  %}"><button class="btn btn-black py-2">Edit Blog</button></a>
                <a href="{% url 'delete_b' detail.id %}"><button class="btn btn-black py-2">Delete</button></a>
            </div>
          {% endif %}
            <div class="pt-5 mt-5">
              <h3 class="mb-5">{{ detail.usercomment_set.count }} Comments</h3>
              <ul class="comment-list">
                {% for i in detail.usercomment_set.all %}
                <li class="comment">
                  <div class="vcard bio">

                    <img src="{{ i.usr.userdetail_set.first.image.url }}" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>{{ i.usr.first_name }}</h3>
                    <div class="meta">{{ i.date }}</div>
                    <p>{{ i.msg }}</p>
                  </div>
                </li>
                {% endfor %}

              </ul>
              <!-- END comment-list -->
              {% if request.user.is_authenticated %}
              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
                <form action="{% url 'comment' detail.id  %}" method="post" class="p-5 bg-light">

                 {% csrf_token %}
                  <div class="form-group">
                    <label for="message">Message</label>
                    <textarea name="msg" id="message" cols="30" rows="10" class="form-control"></textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                  </div>

                </form>
              </div>
              {% endif %}
            </div>

          </div> <!-- .col-md-8 -->
          <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <ul class="categories">
                <h3 class="heading mb-4">Categories</h3>
                <li><a href="#">Travel <span>(12)</span></a></li>
                <li><a href="#">Tour <span>(22)</span></a></li>
                <li><a href="#">Destination <span>(37)</span></a></li>
                <li><a href="#">Drinks <span>(42)</span></a></li>
                <li><a href="#">Foods <span>(14)</span></a></li>
                <li><a href="#">Travel <span>(140)</span></a></li>
              </ul>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Recent Blog</h3>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
                <div class="text">
                  <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
                <div class="text">
                  <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_3.jpg);"></a>
                <div class="text">
                  <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Tag Cloud</h3>
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">dish</a>
                <a href="#" class="tag-cloud-link">menu</a>
                <a href="#" class="tag-cloud-link">food</a>
                <a href="#" class="tag-cloud-link">sweet</a>
                <a href="#" class="tag-cloud-link">tasty</a>
                <a href="#" class="tag-cloud-link">delicious</a>
                <a href="#" class="tag-cloud-link">desserts</a>
                <a href="#" class="tag-cloud-link">drinks</a>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3 class="heading mb-4">Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->

{% endblock %}